version: '3.8'

services:
  bot-manager:
    build: .
    container_name: telegram-bot-manager
    restart: unless-stopped
    environment:
      - MAIN_BOT_TOKEN=${MAIN_BOT_TOKEN}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - MAIN_BOT_ID=${MAIN_BOT_ID}
      - LOCKED_CHANNEL_ID=${LOCKED_CHANNEL_ID}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///bot_manager.db}
      - BOT_REPO_URL=${BOT_REPO_URL}
      - BOT_DEPLOYMENT_DIR=${BOT_DEPLOYMENT_DIR:-/app/deployed_bots}
      - BOT_PYTHON_PATH=${BOT_PYTHON_PATH:-/usr/bin/python3}
      - BANK_CARD_NUMBER=${BANK_CARD_NUMBER}
      - CRYPTO_WALLET_ADDRESS=${CRYPTO_WALLET_ADDRESS}
      - PLAN_1_MONTH=${PLAN_1_MONTH:-30}
      - PLAN_2_MONTHS=${PLAN_2_MONTHS:-60}
      - PLAN_3_MONTHS=${PLAN_3_MONTHS:-90}
      - PRICE_1_MONTH=${PRICE_1_MONTH:-10.00}
      - PRICE_2_MONTHS=${PRICE_2_MONTHS:-18.00}
      - PRICE_3_MONTHS=${PRICE_3_MONTHS:-25.00}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./deployed_bots:/app/deployed_bots
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge